### ISSUE TITLE
Implement api to get data from rspace

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#2992] opened 2020-07-13 08:37 UTC
## Overview
Implement api to get data from rspace
We already got [listeningDataAtName and listeningContinuationAtName](https://github.com/rchain/rchain/blob/c76bd6668cf5f6ddd3acdc44f26fcb08edba08ee/models/src/main/protobuf/DeployServiceV1.proto#L42-L45) although I think they are not very good designed api which can be performance cost.
 We can implement something like [explore_deploy](https://github.com/rchain/rchain/blob/c76bd6668cf5f6ddd3acdc44f26fcb08edba08ee/models/src/main/protobuf/DeployServiceV1.proto#L57), but only for par.

### Impact
No impact for core.

### Dependencies
No

### Design
No

**Comment by zsluedem** [comment] 2020-07-14 03:38
pr for this issue https://github.com/rchain/rchain/pull/2993

**Comment by 9rb** [comment] 2020-12-29 02:22
Closing as the issue is resolved by add new api getDataAtChannel and getContinuationAtChannels #2993

**Closed as completed by 9rb** 2020-12-29 02:22 UTC
Labels: enhancement
