### ISSUE TITLE
Node cannot request Approved block

### ISSUE THREAD

**Issue by nzpr** [rchain/rchain#3118] opened 2020-09-08 07:12 UTC
When debugging LFS, sometimes it can be seen that node cannot receive approved block, thought it requested it.
In addition, there were issues with genesis ceremony tests failing randomly, when some genesis validators does not receive approved block.

With hight degree of confidence this is the fix for that. 
https://github.com/rchain/rchain/pull/3111/commits/872c6eb505bf1883727330dfdf8e568622d0a3ed
The problem is that `init` method of Casper Engine is being read before being initialised on Casper launch.
Won't create separate PR for that because fix is quite simple.

Duplicate issue reported
- #3320

**Comment by nzpr** [comment] 2020-11-01 16:29
Looks like this issue happens when node is restarted with cleaning up the state, so new .pem files generated, and address of node changes. Bootstrap still has old PeerNode associated with IP address and this creates some collision.

**Comment by tgrospic** [comment] 2020-11-23 20:24
In my testing of LFS when I restarted the node with the old state, sometimes the response was not received for approved block. But after deleting pem files worked every time.

**Comment by nzpr** [comment] 2021-01-17 20:06
I believe this issue is not present anymore. @tgrospic are you ok if I close it?

**Comment by tgrospic** [comment] 2021-01-18 13:24
@nzpr I can try to reproduce it again. I can confirm it was still present after PR #3111.

**Comment by tgrospic** [comment] 2021-02-09 09:50
Bug is still present as reported by @gsj5 in a duplicated issue #3320.

**Comment by tgrospic** [comment] 2022-04-30 10:04
Closing because Approved block and existing genesis ceremony will be removed as part of the new multi-parent finalizer.
- #3679

**Closed as completed by tgrospic** 2022-04-30 10:04 UTC
Labels: bug, Priority-Low
