### ISSUE TITLE
Missing response to ApprovedBlockRequest keeps the node waiting forever

### ISSUE THREAD

**Issue by gsj5** [rchain/rchain#3320] opened 2021-02-09 07:55 UTC
On 0.10.0 release, NodeA makes a request for `ApprovedBlockRequest` from NodeB.  NodeB responds with `ApprovedBlock`, however, NodeA never receives the block, making NodeA wait forever for the block.  It would be good to have a timeout and retry N times before exiting.

**Comment by tgrospic** [comment] 2022-01-20 09:45
Closing this issue as duplicate of
- #3118.

**Closed as completed by tgrospic** 2022-01-20 09:45 UTC
Labels: bug, Priority-Low
